apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters
    repoURL: 'git@github.com:jkremser/fosdemo-clusters.git'
    targetRevision: HEAD
  project: default
