# on gcp cluster, run:
# helm repo add k8gb https://www.k8gb.io
# helm repo update
# helm upgrade --install k8gb k8gb/k8gb --namespace k8gb --create-namespace  -f gcp-k8gb-values.yaml
# or to tweak the values
# helm upgrade --reuse-values -n k8gb --set k8gb.clusterGeoTag="eks-eu-west" --set k8gb.extGslbClustersGeoTags="eks-eu-west\,gcp-us-east" k8gb k8gb/k8gb
k8gb:
  dnsZone: "demo.k8s.kremser.dev" # dnsZone controlled by gslb
  edgeDNSZone: "k8s.kremser.dev" # main zone which would contain gslb zone to delegate
  edgeDNSServers: 
  #- "169.254.169.253" # use this DNS server as a main resolver to enable cross k8gb DNS based communication (DNS server for EC2)
  - 1.1.1.1
  clusterGeoTag: "gcp-us-east"
  # comma-separated list of external gslb geo tags to pair with
  extGslbClustersGeoTags: "eks-eu-west,gcp-us-east"

route53:
  enabled: true
  hostedZoneID: Z00685903NFM1HS4Z3B6N
  secret: external-dns

coredns:
  serviceType: LoadBalancer
  service:
    annotations:
      networking.gke.io/load-balancer-type: "External"
  # kubectl create secret -n k8gb generic geodata --from-file=GeoLite2-Country.mmdb
  extraVolumes:
   - name: geo-data 
     emptyDir: {}
  extraVolumeMounts:
   - name: geo-data 
     mountPath: /geoip.mmdb
     subPath: geoip.mmdb


      # volumes:
      # - name: geo-data
      #   emptyDir: {}
      # dnsPolicy: Default
      # initContainers:
      # - name: install
      #   image: busybox
      #   command:
      #   - wget
      #   - "-O"
      #   - "/geo-data/geoip.mmdb"
      #   - https://git.io/GeoLite2-Country.mmdb
      #   volumeMounts:
      #   - name: geo-data
      #     mountPath: "/geo-data"
        # #+ for the main container         
        # volumeMounts:
        # - name: geo-data
        #   mountPath: /geoip.mmdb
        #   subPath: geoip.mmdb